[home]
nome = "Rinaldo Magalhães"
habilidade = "Desenvolvedor Python"
github = "www.github.com/rinaldobsb"
instagram = "www.instagram.com/rinaldo_dev"
quem_sou_eu = "Sou desenvolvedor freelancer. Programo na linguagem Python para Inteligência Artificial e para a Web. Tenho alguns projetos de software feitos. Neste site escrevo algumas coisas e deixo alguns projetos para portifólio."
email = "falecomigo@rinaldo.dev.br"
link_email = "mailto:falecomigo@rinaldo.dev.br"
msg_footer = "BUILDING SOFTWARE WITH ♥ FROM BRASILIA TO THE WORLD."

[projetos]
email = "falecomigo@rinaldo.dev.br"
link_email = "mailto:falecomigo@rinaldo.dev.br"
msg_footer = "BUILDING SOFTWARE WITH ♥ FROM BRASILIA TO THE WORLD."

[blog]
email = "falecomigo@rinaldo.dev.br"
link_email = "mailto:falecomigo@rinaldo.dev.br"
msg_footer = "BUILDING SOFTWARE WITH ♥ FROM BRASILIA TO THE WORLD."